version: '3.8'

services:
  api:
    container_name: neoshare_api
    image: ${REGISTRY}/${PROJECT_NAME}:latest
    networks:
      - neoshare
    environment:
      - APP_ENV=prod
      - PORT=8080

      - AUTH_CLIENT_ID=${AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - AUTH_CALLBACK_URL${AUTH_CALLBACK_URL}
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - AUTH_AUDIENCE=${AUTH_AUDIENCE}

      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET}

      - DB_DATABASE=neoshare
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_HOST=localhost
    ports:
      - "${PORT}:8080"
    depends_on:
      psql:
        condition: service_started

  psql:
    container_name: neoshare_psql
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - neoshare
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:

networks:
  neoshare: