name: goreleaser

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.NS_GH_ACTIONS }}

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Install templ
        shell: bash
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Run templ generate
        shell: bash
        run: templ generate -path .

      - name: Build CSS files
        shell: bash
        run: bun run build

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
          workdir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.NS_GH_ACTIONS }}
